# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhtlVE8Wzx5auzgcRMHTAqRCkbnIsg8F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/smart_parking_30k.csv')
df.head(5)

df.tail()

df.isnull().sum()

df.describe()

df.info()

df['status'].value_counts()

df['status'].value_counts().plot(kind='bar')
plt.title("Parking Status Distribution")
plt.show()

df['floor'].value_counts().sort_index()

df['floor'].value_counts().sort_index().plot(kind='bar')
plt.title("Spots per Floor")
plt.show()

df['type'].value_counts()

df['time_period'].value_counts()

pd.crosstab(df['time_period'], df['status'])

df['distance'].describe()

plt.hist(df['distance'], bins=30)
plt.title("Distance Distribution")
plt.show()

df.groupby('status')['distance'].mean()

df.groupby('user_id')['parking_duration'].mean().head()

pd.crosstab(df['floor'], df['status']).plot(kind='bar', stacked=True)
plt.title("Floor vs Status")
plt.show()

available_spots = df[df['status'] == 0]

def calculate_score(row, preferred_floor=None, preferred_type=None):

    score = 0

    score -= row['distance']

    if preferred_floor:
        score -= abs(row['floor'] - preferred_floor) * 5

    if preferred_type:
        if row['type'] == preferred_type:
            score += 20

    return score

preferred_floor = 1
preferred_type = "normal"

available_spots['score'] = available_spots.apply(
    lambda row: calculate_score(row, preferred_floor, preferred_type),
    axis=1
)

top_recommendations = available_spots.sort_values(by='score', ascending=False).head(5)

top_recommendations

df.groupby('user_id')['floor'].mean()

df[df['time_period'] == 'evening']

df['label'] = (
    (df['status'] == 0) &
    (df['distance'] < df['distance'].quantile(0.3))
).astype(int)

!pip install lightgbm

df_model = pd.get_dummies(df, columns=['type', 'time_period'], drop_first=True)

X = df_model.drop(['label', 'status', 'distance', 'parking_id', 'spot_id', 'user_id'], axis=1)
y = df_model['label']

X = df_model.drop([
    'label',
    'parking_id',
    'spot_id',
    'user_id'
], axis=1)

df_model = df.copy()

df_model = pd.get_dummies(
    df_model,
    columns=['type', 'time_period'],
    drop_first=True
)

df_model = df_model.drop(columns=[
    'parking_id',
    'spot_id',
    'user_id'
])

df_model.dtypes

label = (status == 0 & distance < threshold)

import numpy as np

df['label'] = (
    (df['status'] == 0) &
    (df['distance'] < df['distance'].quantile(0.5))
).astype(int)

noise_idx = np.random.choice(df.index, size=int(0.1 * len(df)), replace=False)
df.loc[noise_idx, 'label'] = 1 - df.loc[noise_idx, 'label']

X = df_model.drop('label', axis=1)
y = df_model['label']

from sklearn.model_selection import train_test_split

X = df_model.drop('label', axis=1)
y = df_model['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

import lightgbm as lgb

model = lgb.LGBMClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=7
)

model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt

lgb.plot_importance(model, max_num_features=10)
plt.show()

model = lgb.LGBMClassifier(
    n_estimators=500,
    learning_rate=0.03,
    num_leaves=31
)